modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mgtcore"
version="1.0.1-SNAPSHOT"
displayName="MGT-Core"
authors="GnomoMuitoLoco"
description='''Esse mod é uma dependência para outros mods MGT e nada mais.'''

[[dependencies.mgtcore]]
modId="neoforge"
type="required"
versionRange="[21.1.211,)"
ordering="NONE"
side="BOTH"

[[dependencies.mgtcore]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
